package com.util;


import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Java8 {

    public void traverse() {
        List<Integer> myList = new ArrayList<Integer>();
        for(int i=0; i<10; i++) {
            myList.add(i);
        }

        myList.forEach(new Consumer<Integer>() {
            @Override
            public void accept(Integer integer) {
                System.out.println("i: " + integer);
            }
        });
    }

    public static void main(String[] args) {
        Java8 java8 = new Java8();
        java8.traverse();
    }
}
